[project]
name = "utilitai"
dynamic = ["version"]
description = "An ergonomic Python Utility AI library"
readme = "README.md"
authors = [
    { name = "Tim Lingard", email = "tklingard@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

license = "MIT"
license-files = ["LICENCE*"]

keywords = ["robotics", "utility AI", "decision intelligence"]

[project.optional-dependencies]
btreeny = ["btreeny>=0.3.0,<0.4"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "btreeny>=0.3.0,<0.4",
    "pyrefly>=0.24.2",
    "pytest>=8.4.1",
    "ruff>=0.16",
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
version_scheme = "no-guess-dev"

[tool.pyrefly]
project-includes = ["src/**/*.py", "tests/**/*.py", "examples/**/*.py"]
[tool.pyrefly.errors]
unused-ignore = true
